name: Build and Push Release

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Vite Build
        run: npm run build
        
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: release
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
